CREATE TABLE Accounts (
  id INT NOT NULL AUTO_INCREMENT,
  account_number VARCHAR(12) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  balance DECIMAL(10,2) DEFAULT 0.00,
  account_type VARCHAR(50) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);
